name: 🪩 Create Gleamy NPM package

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        env:
          NODE_ENV: production
        with:
          node-version: '16.x'
          cache: yarn
      - run: yarn install
      - run: yarn run lint
      - run: yarn run test:coverage
      - run: yarn run ts-coverage
      - name: 🧚🏼‍♀️ Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: output/test/code-coverage.html

  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        env:
          NODE_ENV: production
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
        with:
          always-auth: true
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org/'
          cache: yarn
      - run: yarn install
      - run: yarn run build
      - run: echo "publishing version ${{ env.RELEASE_VERSION }}"
      - run: yarn version ${{ env.RELEASE_VERSION }}
      - run: yarn publish --access=public --allow-same-version --no-git-tag-version
        env:
          NODE_ENV: production
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
