name: 🪩 Create Gleamy NPM package

on:
  release:
    types: [created]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: yarn
    - name: Install dependencies
      run: yarn --frozen-lockfile
      
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: yarn lint
      - run: yarn test:coverage
      - run: yarn ts-coverage
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: output/test/code-coverage.html

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Build artefacts
        run: yarn build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: dist

  # 🪩 publish-gpr:
  #   runs-on: ubuntu-latest
  #       strategy:
  #         matrix:
  #           node-version: [16.x, 17.x, 18.x]
  #           - name: Use Node.js ${{ matrix.node-version }}
            
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #         registry-url: https://npm.pkg.github.com/
  #     - run: npm ci
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
